//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WEB08.AMIS.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WEB08.AMIS.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngừng hoạt động.
        /// </summary>
        public static string ActiveFalse {
            get {
                return ResourceManager.GetString("ActiveFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang hoạt động.
        /// </summary>
        public static string ActiveTrue {
            get {
                return ResourceManager.GetString("ActiveTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D8D8D8.
        /// </summary>
        public static string BackGroundColorHeaderExport {
            get {
                return ResourceManager.GetString("BackGroundColorHeaderExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khắc Tiềm.
        /// </summary>
        public static string DefaultUser {
            get {
                return ResourceManager.GetString("DefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete to database return 0.
        /// </summary>
        public static string DevMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("DevMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete multiple failed.
        /// </summary>
        public static string DevMsg_DeleteMultipleFailed {
            get {
                return ResourceManager.GetString("DevMsg_DeleteMultipleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catched an exception.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert to database return 0.
        /// </summary>
        public static string DevMsg_InsertFailed {
            get {
                return ResourceManager.GetString("DevMsg_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update to database return 0.
        /// </summary>
        public static string DevMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("DevMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input field.
        /// </summary>
        public static string DevMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("DevMsg_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times New Roman.
        /// </summary>
        public static string ExcelFontContent {
            get {
                return ResourceManager.GetString("ExcelFontContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arial.
        /// </summary>
        public static string ExcelFontHeader {
            get {
                return ResourceManager.GetString("ExcelFontHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string GenderOther {
            get {
                return ResourceManager.GetString("GenderOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.api.data_change.
        /// </summary>
        public static string Message_data_change {
            get {
                return ResourceManager.GetString("Message_data_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.api.export_null.
        /// </summary>
        public static string Message_export_null {
            get {
                return ResourceManager.GetString("Message_export_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.api.import_fail.
        /// </summary>
        public static string Message_import_fail {
            get {
                return ResourceManager.GetString("Message_import_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.api.import_success.
        /// </summary>
        public static string Message_import_success {
            get {
                return ResourceManager.GetString("Message_import_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.api.notFoundData.
        /// </summary>
        public static string Message_notFoundData {
            get {
                return ResourceManager.GetString("Message_notFoundData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.google.com/api/errorcode.
        /// </summary>
        public static string MoreInfo_Exception {
            get {
                return ResourceManager.GetString("MoreInfo_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.google.com/api/errorcode.
        /// </summary>
        public static string MoreInfo_InsertFailed {
            get {
                return ResourceManager.GetString("MoreInfo_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.google.com/api/errorcode.
        /// </summary>
        public static string MoreInfo_Request {
            get {
                return ResourceManager.GetString("MoreInfo_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh_sach_nhan_vien.
        /// </summary>
        public static string NameFileExcel {
            get {
                return ResourceManager.GetString("NameFileExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_DeleteMultiple.
        /// </summary>
        public static string Proc_DeleteMultiple {
            get {
                return ResourceManager.GetString("Proc_DeleteMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_DeleteOne.
        /// </summary>
        public static string Proc_DeleteOne {
            get {
                return ResourceManager.GetString("Proc_DeleteOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetAll.
        /// </summary>
        public static string Proc_GetAll {
            get {
                return ResourceManager.GetString("Proc_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetAllActive.
        /// </summary>
        public static string Proc_GetAllActive {
            get {
                return ResourceManager.GetString("Proc_GetAllActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_GetDataByAttribute.
        /// </summary>
        public static string Proc_GetDataByAttribute {
            get {
                return ResourceManager.GetString("Proc_GetDataByAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_GetDataByCheckIncurred.
        /// </summary>
        public static string Proc_GetDataByCheckIncurred {
            get {
                return ResourceManager.GetString("Proc_GetDataByCheckIncurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetDetailOne.
        /// </summary>
        public static string Proc_GetDetailOne {
            get {
                return ResourceManager.GetString("Proc_GetDetailOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetDropdown.
        /// </summary>
        public static string Proc_GetDropdown {
            get {
                return ResourceManager.GetString("Proc_GetDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetFilterExport.
        /// </summary>
        public static string Proc_GetFilterExport {
            get {
                return ResourceManager.GetString("Proc_GetFilterExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetFilterPaging.
        /// </summary>
        public static string Proc_GetFilterPaging {
            get {
                return ResourceManager.GetString("Proc_GetFilterPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetNewCode.
        /// </summary>
        public static string Proc_GetNewCode {
            get {
                return ResourceManager.GetString("Proc_GetNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_Import.
        /// </summary>
        public static string Proc_Import {
            get {
                return ResourceManager.GetString("Proc_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_InsertOne.
        /// </summary>
        public static string Proc_InsertOne {
            get {
                return ResourceManager.GetString("Proc_InsertOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_UpdateActive.
        /// </summary>
        public static string Proc_UpdateActive {
            get {
                return ResourceManager.GetString("Proc_UpdateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_UpdateOne.
        /// </summary>
        public static string Proc_UpdateOne {
            get {
                return ResourceManager.GetString("Proc_UpdateOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có phát sinh bản ghi này với bảng {0}. Bạn phải xóa các phát sinh liên quan trước khi xóa..
        /// </summary>
        public static string UserMsg_CheckIncurred {
            get {
                return ResourceManager.GetString("UserMsg_CheckIncurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá bản ghi thất bại.
        /// </summary>
        public static string UserMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("UserMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá thất bại nhiều bản ghi, hãy tải lại dữ liệu và thử lại.
        /// </summary>
        public static string UserMsg_DeleteMultipleFailed {
            get {
                return ResourceManager.GetString("UserMsg_DeleteMultipleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.api.exception.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhân viên thất bại.
        /// </summary>
        public static string UserMsg_InsertFailed {
            get {
                return ResourceManager.GetString("UserMsg_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin nhân viên thất bại.
        /// </summary>
        public static string UserMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("UserMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string UserMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("UserMsg_ValidateFailed", resourceCulture);
            }
        }
    }
}
